### ISSUE TITLE
when the node is not connectable the driver panics, fix this ugliness

### ISSUE THREAD

**Issue by rsvihladremio** [rsvihladremio/dremio-stress#2]
```pure virtual method called
terminate called after throwing an instance of 'driver::odbcabstraction::CommunicationException'
  what():  Flight returned unavailable error, with message: failed to connect to all addresses. Please ensure your encryption settings match the server.2023/07/26 10:38:15 ERROR: query '[select * FROM Samples."samples.dremio.com"."SF weather 2018-2019.csv" where "DATE" between ':start' and ':end']' failed: 'failed executing query: driver: bad connection'

2023/07/26 10:38:15 ERROR: query '[select * FROM Samples."samples.dremio.com"."SF weather 2018-2019.csv" where "DATE" between ':start' and ':end']' failed: 'failed executing query: driver: bad connection'
SIGABRT: abort
PC=0x7fffffdf3844 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 23 [syscall]:
runtime.cgocall(0x6643c0, 0xc0000408d0)
	/usr/lib/golang/src/runtime/cgocall.go:157 +0x5c fp=0xc0000408a8 sp=0xc000040870 pc=0x406efc
github.com/alexbrainman/odbc/api._Cfunc_SQLDriverConnectW(0x9447a0, 0x0, 0xc0000ae840, 0xfffd, 0x0, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:310 +0x4b fp=0xc0000408d0 sp=0xc0000408a8 pc=0x65a98b

```

**Comment by rsvihladremio** [comment]
no longer applies to the java based version we have now
